export const GET_ACCOUNT_THEME = "GET_ACCOUNT_THEME";
export const SET_ACCOUNT_THEME = "SET_ACCOUNT_THEME";

export const SET_SEARCHBAR_TOGGLE = "SET_SEARCHBAR_TOGGLE";
export const GET_SEARCHBAR_TOGGLE = "GET_SEARCHBAR_TOGGLE";